#!/bin/bash

# Package Gerber files for all boards
# Produces Packages for:
#
#  * OSHPark
#  * DirtyPCBs

# Acquire Script Root
script_root=`dirname ${BASH_SOURCE[0]}`

# Enter Work Directory
init_dir=`pwd`
cd ${script_root}
cd ../proj

# Run through Boards
for board in *.brd
do
	# Fix Board Name
	board=`echo ${board} | sed s/'\.brd'//g`

	# Check Files
	if [ -e ${board}.GML ] && [ -e ${board}.GTL ] && [ -e ${board}.GTO ] && [ -e ${board}.GTS ] && [ -e ${board}.GBL ] && [ -e ${board}.GBO ] && [ -e ${board}.GBS ] && [ -e ${board}.TXT ] && [ -e ${board}.GBP ] && [ -e ${board}.GTP ]
	then
		# Inform
		echo "[+] Packaging Board [ ${board}.zip ]"

		# Package DirtyPCBs
		zip -q ${board}-dirtypcbs.zip ${board}.GTL ${board}.GTO ${board}.GTS ${board}.GBL ${board}.GBO ${board}.GBS ${board}.TXT ${board}.GML ${board}.GBP ${board}.GTP

		# Package OSHPark
		rm -f ${board}-oshpark.zip
		cp ${board}.GML ${board}.GKO
		zip -q ${board}-oshpark.zip ${board}.GTL ${board}.GTO ${board}.GTS ${board}.GBL ${board}.GBO ${board}.GBS ${board}.TXT ${board}.GKO ${board}.GBP ${board}.GTP
	fi
done

# Restore Directory
cd ${init_dir}
