#!/bin/bash

# Package Gerber files for all boards
# for processing by OSHPark

# Acquire Script Root
script_root=`dirname ${BASH_SOURCE[0]}`

# Enter Work Directory
init_dir=`pwd`
cd ${script_root}
cd ../proj

# Loop through Projects
for proj in *
do
	# Inform
	echo "[-] Processing Project [ ${proj} ]"

	# Enter Project Directory
	cd ${proj}

	# Run through Boards
	for board in *.brd
	do
		# Fix Board Name
		board=`echo ${board} | sed s/'\.brd'//g`

		# Inform
		echo "[+] Packaging Board [ ${proj} / ${board}.zip ]"

		# Check Files
		if [ -e ${board}.GML ] && [ -e ${board}.GTL ] && [ -e ${board}.GTO ] && [ -e ${board}.GTS ] && [ -e ${board}.GBL ] && [ -e ${board}.GBO ] && [ -e ${board}.GBS ] && [ -e ${board}.TXT ]
		then
			# Move GML to GKO
			cp ${board}.GML ${board}.GKO

			# Package
			rm -f ${board}-oshpark.zip
			zip ${board}-oshpark.zip ${board}.GTL ${board}.GTO ${board}.GTS ${board}.GBL ${board}.GBO ${board}.GBS ${board}.TXT ${board}.GKO
		else
			# Warn
			echo "[!] Board [ ${proj} / ${board} ] is not ready for packaging - Gerber files not found"
		fi
	done

	# Return to parent Directory
	cd ..
done

# Move GML to GKO
echo $root

# Restore Directory
cd ${init_dir}
